### PR TITLE
Adds some new Items

### PR DESCRIPTION
**Pull request by Odisurin**
Adds a Yellow e-sword
Adds a brown tunic
Adds a WIP Phoron Stun-staff {Sprites are there and basis code is // out for WIP)

Adds brown tunic to loadout select.

### CODE REVIEW

**Comment by Ambrose997** [comment]
You failed to write the parts of the pull request which actually say why this should be added T_T. Wtf is the phoron-stun staff for??

**Comment by Odisurin** [comment]
I don't need those.

**Comment by Ambrose997** [comment]
wat?

**Comment by Ambrose997** [comment]
Personally I don't care about the cosmetic changes but the phoron stunstick is more powerful than the normal one, and I don't see any reason why we'd need more stun-based weaponry in the game. But that's just my take.

**Comment by Odisurin** [comment]
Its a tool for research to research, not really an off the bat weapon. Its not fully implemented.

**Comment by Odisurin** [comment]
And when I say "staff" I don't mean "Wizard" I mean polearm. meaning its a wielded stun weapon that takes up both hands and will not fit in a bag.

**Comment by Ambrose997** [comment]
that sounds really odd for the setting for research to... make a futuristic stunning spear.

**Pull request closed without merging**
