### PR TITLE
Whitelist to fit current governor positions change

### PR DESCRIPTION
**Pull request by hako01**
## About The Pull Request

updates the WL to fit the governor cabinet, the change to polaris.dme is purely to stop the old map warning from popping, does virtually nothing else

## Changelog
:cl:
add: some whitelisted some govrnor cabinet players
tweak: stopped dream maker enviroment from trying to load the old geminus map and failing each compile
:cl:

### CODE REVIEW

**Comment by hako01** [comment]
removed the twerk emote from this PR, since it was a mistake

**Comment by GeneriedJenelle** [comment]
angrypotato's ckey has an underscore, you make need to exclude the _ to make it work.

**Comment by YourPalHolidays** [comment]
> angrypotato's ckey has an underscore, you make need to exclude the _ to make it work.

Yes, in Ckey whitelists, make sure that all underscores are removed and all letters are not capitalized.

**Comment by hako01** [comment]
there is something wrong here

**Pull request closed without merging**
