### PR TITLE
fixed things in map v2

### PR DESCRIPTION
**Pull request by hako01**
## About The Pull Request

following these threads
https://discord.com/channels/1140295392550994043/1155305728601489459
https://discord.com/channels/1140295392550994043/1157390822287867964
https://discord.com/channels/1140295392550994043/1157113025464115310

## Changelog
:cl:
fix: fixed loot piles on upper and lower that had the wrong type assigned to them as a spawner
change: changed prosecutor office to have it's own department ID for the fax, same for defense obviously with a different department ID
fix: fixed psych windoors to have psych access attached to them
/:cl:

### CODE REVIEW

**Comment by YourPalHolidays** [comment]
There is a conflict with maps/geminus_kiel/geminus_neue-3.dmm, please address it.

**Comment by hako01** [comment]
not sure what caused it, will revert changes and recommit them maybe I deleted a zone or duplicated something

**Comment by Odisurin** [comment]
Did you keep your branch up to the current branch version?

**Comment by hako01** [comment]
> Did you keep your branch up to the current branch version?

yep, unless around the time i pr'd something else was merged

**Comment by Odisurin** [comment]
Dunno, this is usually the thing that drives me mad when I try to contribute.. You work hours at a time to get a PR through just for other content to be merged and you gotta do it over. But that's just me.

**Comment by hako01** [comment]
> Dunno, this is usually the thing that drives me mad when I try to contribute.. You work hours at a time to get a PR through just for other content to be merged and you gotta do it over. But that's just me.

it's just a simple revert for me, so far I'm not doing anything major, all I've done could be contributed in 30min or less by any experienced mapper

**Comment by hako01** [comment]
image
so uhhh, this is something I can't debug in a single evening but I will try to rework this, gonna cancel the loot pile fix, only fix psych ID access, the conflict is in the map hash which I literally cannot read not sure why it's conflicting there even

**Comment by hako01** [comment]
and now my github desktop broke greattt

**Comment by hako01** [comment]
> There is a conflict with maps/geminus_kiel/geminus_neue-3.dmm, please address it.

conflict removed, however this conflict still needs to be checked

**Comment by Odisurin** [comment]
Is it possibly from the prior fixes to noteboards?

**Comment by YourPalHolidays** [comment]
It seems the conflict has been resolved.

**Comment by hako01** [comment]
I'll open a separate PR for the lootpiles I think I found something funny and why it conflicts, the conflicts on this PR is fully gone, however there is no lootpile changes

**Comment by YourPalHolidays** [comment]
Alright, merging.

**Pull request merged**
