### PR TITLE
governor overhaul

### PR DESCRIPTION
**Pull request by hako01**
## About The Pull Request

minor changes to govportal + addition of vice gov

## Changelog
:cl:
add: Added vice governor
add: Added correct ID, outfit, job joining method and whitelisting
del: Removed mentions of being president from gov portal 
tweak: changed president outfit with a governor one removing visible connections of the governor being a repainted president job
tweak: replaced instances where "president", "presidential" is mentioned visibly in govportal replaced with "colonial", "government" where appropriate.

/:cl:

### CODE REVIEW

**Comment by YourPalHolidays** [comment]
Please post a screenshot of your changes successfully compiling in DreamMaker.

**Comment by hako01** [comment]
image

**Comment by YourPalHolidays** [comment]
Conflict with: maps/geminus_kiel/geminus_neue-2.dmm

**Comment by Odisurin** [comment]
I was pushing an update and was about to test it again.
Why you merge it?... ._.

**Comment by Odisurin** [comment]
I was in the mid process of adding more to the PR...

**Pull request merged**
